# Generated by Django 3.2.6 on 2021-08-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210809_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
